services:
  # --- THE BACKEND SERVICE ---
  fastapi-backend:
    image: prakhar869/discusso-backend:latest
    healthcheck:
      # Python's built-in library to check the URL
      test:
        [
          "CMD-SHELL",
          'python3 -c ''import urllib.request; urllib.request.urlopen("http://localhost:8000/health")'' || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s # Gives the ML model time to load weights before checking
    container_name: discusso-api
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - ML_INTERNAL_SECRET=${ML_INTERNAL_SECRET}
    networks:
      - discusso-net

  # --- THE FRONTEND SERVICE ---
  nextjs-frontend:
    build: .
    container_name: discusso-web
    ports:
      - "3000:3000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - ML_INTERNAL_SECRET=${ML_INTERNAL_SECRET}
      - ML_URL=${ML_URL}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
    networks:
      - discusso-net
    depends_on:
      fastapi-backend:
        condition: service_healthy

# --- THE SHARED NETWORK ---
networks:
  discusso-net:
    driver: bridge
